<?php
// $Id$

/**
 * @file
 * Provides configuration page to choose a menu to pull items from and create a custom menu using those items.
 */

function company_info_form_system_site_information_settings_alter(&$form, &$form_state) {
  $form['company_info'] = array(
    '#type' => 'fieldset',
    '#title' => t('Company Information'),
    '#weight' => 1,
  );
  $form['company_info']['desc_text'] = array(
    '#markup' => t('This information will be stored in variables for use in template files.'),
  );
  $form['company_info']['co_address'] = array(
    '#type' => 'textfield',
    '#title' => t('Street Address'),
    '#maxlength' => 128,
    '#default_value' => variable_get('co_address', ''),
    '#required' => TRUE,
  );
  $form['company_info']['co_city'] = array(
    '#type' => 'textfield',
    '#title' => t('City'),
    '#maxlength' => 128,
    '#default_value' => variable_get('co_city', ''),
    '#required' => TRUE,
  );
  $form['company_info']['co_state'] = array(
    '#type' => 'textfield',
    '#title' => t('State/Province'),
    '#maxlength' => 128,
    '#default_value' => variable_get('co_state', ''),
    '#required' => TRUE,
  );
  $form['company_info']['co_zip'] = array(
    '#type' => 'textfield',
    '#title' => t('Postal Code'),
    '#maxlength' => 10,
    '#default_value' => variable_get('co_zip', ''),
    '#required' => TRUE,
  );
  $form['company_info']['co_phone'] = array(
    '#type' => 'textfield',
    '#title' => t('Phone Number'),
    //'#maxlength' => 12,
    '#default_value' => variable_get('co_phone', ''),
    '#required' => TRUE,
  );
  $form['company_info']['co_phone2'] = array(
        '#type' => 'textfield',
        '#title' => t('Alternate Phone Number'),
        //'#maxlength' => 12,
        '#default_value' => variable_get('co_phone2', ''),
        //'#required' => TRUE,
    );
}
